### PR TITLE
Update documentation when master branch is changed

### PR DESCRIPTION
**Pull request by niklasnatter**

### CODE REVIEW

**Comment by luca-rath** [comment]
@nnatter @alexander-schranz I think this pr should be reverted, because when the action is triggered by `sulu/sulu`, it pushes the generated styleguide to the master branch, and then the action is triggered again, because of that push

**Comment by niklasnatter** [comment]
you are right - why is this not causing a loop right now? 😮

**Comment by luca-rath** [comment]
I don't think so ... probably github prevents that, if the push is triggered by a workflow of the same repository

**Comment by niklasnatter** [comment]
Okay looks like a push inside of an action does not trigger the action:
https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854

In that case, I dont think we should revert it 🙁

**Comment by luca-rath** [comment]
If you see the commit history, there are always 2 builds for every triggered workflow by sulu now

**Comment by luca-rath** [comment]
And it's not really needed, because you can also manually trigger this action here https://github.com/sulu/sulu-javascript-docs/actions?query=workflow%3A%22Update+Documentation%22  by pressing `Run workflow`

**Comment by niklasnatter** [comment]
Yes, but you have to think about that 🙈  

Are you sure that the build is triggered two times? I dont see the duplicated builds here:
https://github.com/sulu/sulu-javascript-docs/actions

**Comment by niklasnatter** [comment]
If the build is executed because of a push, the run will look like this:
https://github.com/sulu/sulu-javascript-docs/actions/runs/319271774

**Comment by luca-rath** [comment]
I'm going to trigger the workflow manually now so we can check that

**Comment by luca-rath** [comment]
okay, I think you were right ... No need to revert this 🙂

**Comment by niklasnatter** [comment]
Okay thats good 🙂

**Pull request merged**
